<a href="https://colab.research.google.com/github/makarun99/KSVD/blob/main/%D0%91%D0%B0%D0%B1%D0%B8%D1%87_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Лабораторна робота №1: Аналіз даних
# Студент: Бабич Марко
# Предмет: Комп'ютерні системи візуалізації даних

import numpy as np

# 1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.
vector_20 = np.arange(1, 21)
print("Одновимірний масив з перших 20 натуральних чисел:\n", vector_20)

# 2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.
matrix_4x4 = np.ones((4, 4))
print("\nМатриця 4x4, заповнена одиницями:\n", matrix_4x4)

# 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.
random_5x5 = np.random.uniform(-1, 1, (5, 5))
print("\nМатриця 5x5 з випадковими числами [-1, 1]:\n", random_5x5)

# 4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
random_3x3 = np.random.rand(3, 3)
print("\nМатриця 3x3 з випадковими числами [0, 1]:\n", random_3x3)

# 5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20
a = np.random.randint(1, 21, 6)
b = np.random.randint(1, 21, 6)
print("\nМасив A:", a)
print("Масив B:", b)

# Поелементні операції
print("A + B:", a + b)
print("A - B:", a - b)
print("A * B:", a * b)

# 6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
mat1 = np.random.randint(1, 6, (3, 2))
mat2 = np.random.randint(1, 6, (2, 4))
product = np.dot(mat1, mat2)
print("\nМатриця 3x2:\n", mat1)
print("Матриця 2x4:\n", mat2)
print("Результат множення 3x2 * 2x4:\n", product)

# 7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
mat_trans = np.random.rand(3, 3)
print("\nОригінальна матриця 3x3:\n", mat_trans)
print("Транспонована матриця:\n", mat_trans.T)

# 8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
mat_a = np.random.randint(1, 11, (3, 3))
mat_b = np.random.randint(1, 11, (3, 3))
diff = mat_a - mat_b
print("\nМатриця A:\n", mat_a)
print("Матриця B:\n", mat_b)
print("Різниця A - B:\n", diff)

# 9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.
mat_c = np.random.randint(-5, 6, (3, 3))
mat_d = np.random.randint(-5, 6, (3, 3))
product2 = np.dot(mat_c, mat_d)
print("\nМатриця C:\n", mat_c)
print("Матриця D:\n", mat_d)
print("Добуток C * D:\n", product2)

# 10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
mat_e = np.random.uniform(-1, 1, (3, 3))
row_sums = np.sum(mat_e, axis=1).reshape(-1, 1)
print("\nМатриця 3x3 з числами [-1, 1]:\n", mat_e)
print("Сума елементів кожного рядка (вектор-стовпчик):\n", row_sums)

Одновимірний масив з перших 20 натуральних чисел:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Матриця 4x4, заповнена одиницями:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Матриця 5x5 з випадковими числами [-1, 1]:
 [[-0.4400332   0.09716076  0.50623158  0.22299811 -0.91409877]
 [-0.94232177 -0.61022845  0.42571375  0.46631596  0.49907886]
 [-0.96817413 -0.05473292  0.06062842  0.83313548 -0.11297654]
 [ 0.98365459 -0.19186086  0.6614768  -0.06757936  0.34303365]
 [ 0.21893892 -0.47030905 -0.13207963  0.67775937  0.57718031]]

Матриця 3x3 з випадковими числами [0, 1]:
 [[0.14001074 0.22258153 0.80671042]
 [0.08610678 0.34394116 0.02687373]
 [0.48588365 0.41832978 0.78310849]]

Масив A: [16 11 12 12 14  3]
Масив B: [18 20  1 11  6  4]
A + B: [34 31 13 23 20  7]
A - B: [-2 -9 11  1  8 -1]
A * B: [288 220  12 132  84  12]

Матриця 3x2:
 [[3 2]
 [5 2]
 [3 4]]
Матриця 2x4:
 [[4 1 2 3]
 [4 3 2 4]]
Результат множення 3x2 * 2x4:
 [[20  9 10 17]
 [28 11 14